
networks:
  simplilearn-phpinfo-network:
    internal: false
    
secrets:
  src:
    file: ./src/index.php
    
services:
  simplilearn-phpinfo:
    command:
      - -f
      - index.php
      - -S
      - 0.0.0.0:8080
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 2
    entrypoint: /usr/bin/php
    environment:
      OWNER: Sebastian
    image: academiaonline/simplilearn-phpinfo:1.1
    networks:
      - simplilearn-phpinfo-network
    ports:
      - 84:8080
    secrets:
      -
        gid: 65534
        mode: 400
        source: src
        target: /src/index.php
        uid: 65534
    user: nobody
    working_dir: /src/
    
version: '3.8'    

# docker stack deploy --compose-file docker-compose-secret.yaml SIMPLILEARN-PHPINFO-SECRET
